import React,{useRef,useState} from 'react';import{createRoot}from'react-dom/client';import{Camera,Mic,Play,Square,Music2,Sparkles,Hand,Download}from'lucide-react';import * as Tone from'tone';import'./styles.css';
const chords=[['C',['C4','E4','G4']],['Am',['A3','C4','E4']],['F',['F3','A3','C4']],['G',['G3','B3','D4']]];
function App(){const video=useRef<HTMLVideoElement>(null);const media=useRef<MediaStream|null>(null);const rec=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const[cam,setCam]=useState(false);const[recording,setRecording]=useState(false);const[url,setUrl]=useState('');const[current,setCurrent]=useState('');
async function startCamera(){const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:true});media.current=s;if(video.current){video.current.srcObject=s;await video.current.play()}setCam(true)}
async function chord(name:string,notes:string[]){await Tone.start();const synth=new Tone.PolySynth(Tone.Synth).toDestination();synth.triggerAttackRelease(notes,'2n');setCurrent(name);setTimeout(()=>setCurrent(''),500)}
function toggleRecord(){if(!media.current)return;if(!recording){chunks.current=[];const r=new MediaRecorder(media.current);r.ondataavailable=e=>chunks.current.push(e.data);r.onstop=()=>{const b=new Blob(chunks.current,{type:'video/webm'});setUrl(URL.createObjectURL(b))};r.start();rec.current=r;setRecording(true)}else{rec.current?.stop();setRecording(false)}}
return <><nav><div className="brand"><span>V</span>VOXMIO</div><div className="navlinks"><a href="#studio">Studio</a><a href="#how">How it works</a><a href="#pricing">Pricing</a></div><button onClick={()=>document.getElementById('studio')?.scrollIntoView({behavior:'smooth'})}>Start creating</button></nav>
<header><div className="eyebrow"><Sparkles size={14}/> MUSIC, WITHOUT THE BARRIERS</div><h1>The music in your head<br/><em>shouldn't stay there.</em></h1><p>Use your hands to play. Use your voice to create. Voxmio turns musical instinct into something you can hear, record and share.</p><div className="actions"><button className="primary" onClick={()=>document.getElementById('studio')?.scrollIntoView({behavior:'smooth'})}><Play size={17}/> Try the studio</button><span>No instrument. No theory. Just create.</span></div></header>
<section id="studio" className="studio"><div className="studioHead"><div><small>LIVE PLAYGROUND</small><h2>Make something now.</h2></div><div className="live"><i/> {cam?'CAMERA LIVE':'READY'}</div></div><div className="workspace"><div className="camera"><video ref={video} muted playsInline/><div className="cameraEmpty" style={{display:cam?'none':'flex'}}><Hand/><b>Your hands become the instrument.</b><p>Enable your camera and microphone to enter the studio.</p><button onClick={startCamera}><Camera size={17}/> Enable camera + mic</button></div>{cam&&<div className="hud"><span>HAND SPACE</span><strong>{current||'Move. Sing. Create.'}</strong></div>}</div><aside><h3>Gesture chords</h3><p>Prototype controls — tap a chord now. Hand recognition is the next layer.</p><div className="chords">{chords.map(([n,notes])=><button key={n as string} onClick={()=>chord(n as string,notes as string[])}><span>{n as string}</span><small>PLAY</small></button>)}</div><div className="rec"><button disabled={!cam} className={recording?'stop':''} onClick={toggleRecord}>{recording?<><Square size={16}/> Stop recording</>:<><Mic size={16}/> Record performance</>}</button></div>{url&&<div className="take"><Music2/><div><b>Your first take</b><audio src={url} controls/></div><a href={url} download="voxmio-take.webm"><Download size={18}/></a></div>}</aside></div></section>
<section id="how" className="features"><article><Hand/><small>01</small><h3>Play with your hands</h3><p>Camera-based gestures become chords and musical controls.</p></article><article><Mic/><small>02</small><h3>Sing the idea</h3><p>Capture your voice while Voxmio gives you an instrument underneath it.</p></article><article><Sparkles/><small>03</small><h3>Make it bigger</h3><p>AI harmonies, accompaniment and simple production tools come next.</p></article></section>
<section id="pricing" className="pricing"><small>THE BUSINESS MODEL</small><h2>Free to play.<br/><em>Pay to create seriously.</em></h2><div><p>Everyone gets the magic first. Creator unlocks full projects, exports, more instruments and AI enhancements.</p><button>Creator coming soon</button></div></section><footer><div className="brand"><span>V</span>VOXMIO</div><p>More people creating a more musical world.</p><small>© 2026 Voxmio</small></footer></>}
createRoot(document.getElementById('root')!).render(<App/>);